POST http://127.0.0.1:3000/auth/register
Content-Type: application/json 

{
    "name":"linavargas",
    "mail":"lina@gmail.com",
    "password": "123456"
}

### login sin conexion a BDD
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json 

{
    "name":"linavargas",
    "email":"lina@gmail.com",
    "password": "123456"
}


### users

GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxpbmFAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTczMzI0MDUzMiwiZXhwIjoxNzMzMjQwNTkyfQ.3wd--Dsy_nI8g3t2ODmshKN2bg9TXdNmKCKHYBXwNNA