### Listar productos
GET http://localhost:3000/producto

### Crear producto
POST http://localhost:3000/producto
Content-Type: application/json

{
    "nombre": "impresora Laser",
    "precio": "500.95",
    "stock": 12,
    "categoriaId": 1
}
